name = "Patterns"
uuid = "2ab4f8df-f17a-47f3-bf94-541b2ac2cddd"
authors = ["Cursor Insight <info@cursorinsight.com>"]
version = "0.3.2"

[deps]
MacroTools = "1914dd2f-81c6-5fcd-8719-6d5c9610ff09"

[compat]
julia = "1.7"
